apiVersion: apps/v1
kind: Deployment
metadata:
  name: apifraud
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apifraud
  template:
    metadata:
      labels:
        run: apifraud
    spec:
      containers:
        - name: apifraud
          image: api-fraud:1
          ports:
            - containerPort: 3000
          env:
            - name: GET_HOSTS_FROM
              value: dns