apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  labels:
    run: fraud-service
spec:
  type: LoadBalancer
  selector:
    run: apifraud
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
