apiVersion: apps/v1
kind: Deployment
metadata:
  name: appverify
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appverify
  template:
    metadata:
      labels:
        run: appverify
    spec:
      containers:
        - name: appverify
          image: app-verify:4
          ports:
            - containerPort: 3001
          env:
            - name: GET_HOSTS_FROM
              value: dns