apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apigateway
  template:
    metadata:
      labels:
        run: apigateway
    spec:
      containers:
        - name: apigateway
          image: apigateway:3
          ports:
            - containerPort: 3000
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: APP_NAME
              value: apigateway
            - name: CUSTOMER_ENDPOINT
              value: apicustomer-svc:4002
            - name: ACCOUNT_ENDPOINT
              value: apiaccount-svc:4003
            - name: FRAUD_ENDPOINT
              value: apifraud-svc:4004
            - name: OFFER_ENDPOINT
              value: apioffer-svc:4005
