apiVersion: v1
kind: Service
metadata:
  name: offer-service
  labels:
    run: offer-service
spec:
  type: LoadBalancer
  selector:
    run: apioffer
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3000
