apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  type: LoadBalancer
  selector:
    run: apiaccount
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
