apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    run: product-service
spec:
  type: NodePort
  selector:
    run: apiproduct
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 8010
