apiVersion: v1
kind: Service
metadata:
  name: x
  namespace: x
  labels:
    alias: localhost
    run: x
spec:
  type: NodePort
  selector:
    run: x
  ports:
    - protocol: TCP
      port: x
      targetPort: x
