apiVersion: apps/v1
kind: Deployment
metadata:
  name: x
  namespace: x
spec:
  replicas: 1
  selector:
    matchLabels:
      run: x
  template:
    metadata:
      labels:
        run: x
    spec:
      containers:
        - name: x
          image: x
          ports:
            - containerPort: x
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: CUSTOMER_ENDPOINT
              value: customer-service:3000
            - name: ACCOUNT_ENDPOINT
              value: account-service:3001
            - name: FRAUD_ENDPOINT
              value: fraud-service:3002
            - name: OFFER_ENDPOINT
              value: offer-service:3003
